### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by nikky-k** [mchristopher/PokemonGo-DesktopMap#102]
I'm on Mac OSX El Capitan and I'm using Version 0.0.7 of the program. The program has been working fine all day and then when I've tried to log in the last 45 minutes, this pops up.

Uncaught Exception:
Error: This socket is closed
    at Socket._writeGeneric (net.js:672:19)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:650:40)
    at Timeout._onTimeout (/Users/brandonmitchener/Desktop/Pokemon GO Live Map.app/Contents/Resources/app/main.js:270:21)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by doctor-ew** [comment]
Same error. OSX yosemite

**Comment by andrewda** [comment]
I believe the PokemonGo-Map python script is not working for you guys - it's crashing when run. Try running PokemonGo-Map and seeing what errors are output when run.

**Comment by AVellucci** [comment]
@nikky-k @doctor-ew  Can you confirm if this is still an issue in the current releases(0.2.1)?
