### ISSUE TITLE
"Help Wanted" peewee.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by Tchitan** [mchristopher/PokemonGo-DesktopMap#1147]
Hi. 
I am using this gorgeous app now for few weeks and really people thank you all for the effort. And with the last update and adding the multi account it got even better. But now to my issue. On my PC everything works without any problem. But I am trying to install it on the PC of my wife (Win10 64x, app version 0.34) and when I start the app it just says "Loading, please wait..." I am using a verified PTC account which works on my PC. When I opened the developer console in the app I have found this (I have replaced the win user name by "...") in the log:

server up: null
Error getting location, trying second provider PositionError
2016-09-03 06:36:49,467 [      MainThread][     runserver][    INFO] Parsed location is: 48.8178/2.2870/69.9708 (lat/lng/alt)

2016-09-03 06:36:49,470 [      MainThread][        models][    INFO] Connecting to local SQLite database

Traceback (most recent call last):
  File "./run_map.py", line 36, in <module>
    main()
  File "C:\Users...\AppData\Local\pokemon\app-0.3.4\resources\app\map\runserver.py", line 163, in main
    create_tables(db)
  File "C:\Users...\AppData\Local\pokemon\app-0.3.4\resources\app\map\pogom\models.py", line 900, in create_tables
    db.connect()
  File "C:\Users...\AppData\Local\pokemon\app-0.3.4\resources\app\packages.zip\peewee.py", line 3404, in connect
  File "C:\Users...\AppData\Local\pokemon\app-0.3.4\resources\app\packages.zip\peewee.py", line 3316, in **exit**
  File "C:\Users...\AppData\Local\pokemon\app-0.3.4\resources\app\packages.zip\peewee.py", line 3402, in connect
  File "C:\Users...\AppData\Local\pokemon\app-0.3.4\resources\app\packages.zip\peewee.py", line 3658, in _connect
peewee.OperationalError: unable to open database file

Found location [49.4403,11.0809] by ipinfo.io
# 

Any ideas how to make it work? 
Thanks

**Comment by imdanielsp** [comment]
No solution for this problem yet?
