### ISSUE TITLE
Cant get the map to scan

### ISSUE THREAD

**Issue by vicstarrr** [mchristopher/PokemonGo-DesktopMap#1189]
IM getting this error when i launch the scan

Error: connect ECONNREFUSED 127.0.0.1:8000
   at Object.exports._errnoException (util.js:949:11)
   at exports._exceptionWithHostPort (util.js:972:20)
   at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)

does anyone else get the same error?

**Comment by Sedare** [comment]
I only get this when I use the logout button on the top left, and log back in within 15 seconds. Close the javascript error and it disappears for me in 10 seconds.
