### ISSUE TITLE
Database Locked after 5 minutes of scanning

### ISSUE THREAD

**Issue by kezc7** [mchristopher/PokemonGo-DesktopMap#1309]
Using the 0.4.1 release on Windows 10 and scanning with 2 accounts. Within 5 minutes of the map being started, the status changes to Outage. I have another map with 1 worker and it has been running fine all day. Any help would be appriciated :)

On checking the console, i see the following:

[2016-11-07 21:54:38,733] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask_cors\extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\map\pogom\app.py", line 167, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng, timestamp=timestamp)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\map\pogom\models.py", line 140, in get_active
    for p in query:
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-11-07 21:54:38,733 [      Thread-287][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask_cors\extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\map\pogom\app.py", line 167, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng, timestamp=timestamp)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\map\pogom\models.py", line 140, in get_active
    for p in query:
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Users\pokescan\AppData\Local\pokemon\app-0.4.1\resources\app\packages.zip\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

2016-11-07 21:54:42,707 [      db-cleaner][        models][    INFO] Regular database cleaning complete

**Comment by kezc7** [comment]
I managed to fix this by switching to a mysql database. no more locks!
