### ISSUE TITLE
Specifying lat/lng throws AttributeError

### ISSUE THREAD

**Issue by xan0v** [mchristopher/PokemonGo-DesktopMap#15]
Great work on this! Very cool. For some reason, sometimes when plugging in custom lat/lng coords, _sometimes_ the map will not load and throws the following AttributeError:

```
Traceback (most recent call last):
  File "packages.zip\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "packages.zip\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "packages.zip\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "packages.zip\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "packages.zip\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "packages.zip\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alex\Desktop\PokemonGoMap-Win\resources\app\map\example.py", line 807, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "C:\Users\Alex\Desktop\PokemonGoMap-Win\resources\app\map\example.py", line 918, in get_map
    zoom='15', )
  File "C:\Users\Alex\Desktop\PokemonGoMap-Win\resources\app\map\flask_googlemaps\__init__.py", line 43, in __init__
    self.build_markers(markers)
  File "C:\Users\Alex\Desktop\PokemonGoMap-Win\resources\app\map\flask_googlemaps\__init__.py", line 79, in build_markers
    self.add_marker(**marker)
  File "C:\Users\Alex\Desktop\PokemonGoMap-Win\resources\app\map\flask_googlemaps\__init__.py", line 102, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required
```

**Comment by ilikesomething** [comment]
Same problem, and if it can help, it doesn't happen everytime.
Usually i got this error the first and second try (relaunching the app and loginin without or with custom coordinate) and the third try it sometimes pass and work

**Comment by BriseRotule** [comment]
It's really not permissive, you have to have the right number of decimal. That did the trick for me.

**Comment by stephenhcha** [comment]
Same problem:
AttributeError: lat and lng required
Seems to happen when closing and reopening the program frequently.  
It doesn't matter if you choose to manually input coordinates or leave it blank.

**Comment by wmwinn** [comment]
I resolved this error by removing all Python processes in Task Manager, then re-starting.

**Comment by mchristopher** [comment]
Generally this is an issue with old Python processes running. It should be fixed in the latest version, but if not try restarting the computer and running it again.
