### ISSUE TITLE
Loading Please Wait

### ISSUE THREAD

**Issue by chpoint** [mchristopher/PokemonGo-DesktopMap#545]
hi to all, i have install this app recently but, i some bug 5 min in there 
[Imgur](http://i.imgur.com/49As4Tr.jpg)

**Comment by 4okave** [comment]
So any ideas?

My problem is - on one PC at work, it works, on another PC at home it doesn't.

Same says please wait forever, Both computers Win10. Tried everything simple.

**Comment by RazorShaman** [comment]
and where is a decision?

**Comment by jmbarnes1987** [comment]
I'm showing the following in the Node.js log:

Python: <MY PATH>\PokemonGo\PokemonGo-DesktopMap-master\pywin\python.exe: can't open fil
e './runserver.py': [Errno 2] No such file or directory

**Comment by jmbarnes1987** [comment]
npm ERR! Failed at the pokemon-go-map@0.1.6 postinstall script 'cd ./map/ && pip install -r requirem
ents.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-go-map package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./map/ && pip install -r requirements.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-go-map
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-go-map
npm ERR! There is likely additional logging output above.

**Comment by jmbarnes1987** [comment]
I had this issue, but then realized I only cloned this Repo and not the Map repo as well. Not sure if that's what the deal is with everyone else. If you have an empty Map folder, that's probably the issue.

**Comment by jmbarnes1987** [comment]
Ran into a couple more issues afterwards, but long story short, it works!! If anyone is having this issue, I recommend reading the messages displayed when you execute 'npm install' and 'npm start'. You will find the source of your problems in there.

**Comment by 4okave** [comment]
> 
 I recommend reading the messages displayed when you execute 'npm install' and 'npm start'. You will find the source of your problems in there.

what do you mean? where do I read this? I dont execcute anything) just trying to load the map via .exe

**Comment by jokerO0o** [comment]
same here, im using the . exe can someone give us an clear answera about what to do in this case?

**Comment by jersten** [comment]
On latest release have ran into same issue on Linux mint 18. After looking in the debug console I'm seeing:

```
    import xxhash
ImportError: No module named xxhash
```

Attempted installation with `pip` to no avail; error does not go away.

**Comment by ccossou** [comment]
I installed xxhash. The import then works correctly but the API is all white with only the option, without any maps or icons. The error I got before the tracking started were all of the same order : 
`Python server started!
Got open express port: 8001
Express listening on port 8001
Express server started!
Python: [2016-08-16 17:14:12,778] ERROR in app: Exception on /static/dist/css/app.min.css [GET]
Traceback (most recent call last):
  File "packages.zip/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "packages.zip/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "packages.zip/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "packages.zip/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "packages.zip/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "packages.zip/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "packages.zip/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "packages.zip/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
2016-08-16 17:14:12,778 [        Thread-8][           app][   ERROR] Exception on /static/dist/css/app.min.css [GET]
Traceback (most recent call last):
  File "packages.zip/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "packages.zip/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "packages.zip/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "packages.zip/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "packages.zip/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "packages.zip/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "packages.zip/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "packages.zip/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
`
