### ISSUE TITLE
Error when re-launching the application causes a python process to eat memory

### ISSUE THREAD

**Issue by ApocUSB190** [mchristopher/PokemonGo-DesktopMap#6]
Hello,
I have found what I believe is a bug.  When I launch the application, I am allowed to log in and use the application as described.  However, if I close and relaunch an application, a bunch of errors are thrown.  The entire error log is at the bottom of this post.  [As you can see in the video I attached](https://www.youtube.com/watch?v=CqO0Gi8ps9M), it works fine on the first run.  On the second run, at 0:40 in the video is when the error is thrown.  The big issue here is that a new python process is created, which allocates 1.9 GB of RAM to itself, and does NOT terminate when you close the application.  At 1:02, you can see the application closed and the python process remaining.  I recreate the bug again in the video, and you can see that the second time around it still leaves a python process open after the application is closed and it is also taking 1.9 GB of RAM.

Traceback (most recent call last):
  File "packages.zip\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "packages.zip\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "packages.zip\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "packages.zip\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "packages.zip\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "packages.zip\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\David_Gaming\Desktop\New folder (2)\resources\app\map\example.py", line 807, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "C:\Users\David_Gaming\Desktop\New folder (2)\resources\app\map\example.py", line 918, in get_map
    zoom='15', )
  File "C:\Users\David_Gaming\Desktop\New folder (2)\resources\app\map\flask_googlemaps\__init__.py", line 43, in __init__
    self.build_markers(markers)
  File "C:\Users\David_Gaming\Desktop\New folder (2)\resources\app\map\flask_googlemaps\__init__.py", line 79, in build_markers
    self.add_marker(**marker)
  File "C:\Users\David_Gaming\Desktop\New folder (2)\resources\app\map\flask_googlemaps\__init__.py", line 102, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required

**Comment by lopezloo** [comment]
Looks like python process remain alive after closing app.

**Comment by Portical** [comment]
Yeah I notice this too. I have to close the pyton service before re-opening the app.

**Comment by mchristopher** [comment]
This has been fixed in 0.0.3. I'm going to close it for now. Please open a new issue if the problem still exists.
