### ISSUE TITLE
Can't run 0.2.1 in ubuntu 16.04

### ISSUE THREAD

**Issue by FernandoGBR** [mchristopher/PokemonGo-DesktopMap#682]
Thanks for your time:

I have just tried to run the 0.2.1 in my ubuntu 16.04 machine and i have the following console trace when i end the google login (just after accepting the permisions):

Starting Python process...
Got open python port: 8000
Maps path: /home/kazeta/pokemongomap/resources/app/map
python ./runserver.py --cors --auth-service google --location=40.4172000,-3.6840000 --port 8000 --db /home/kazeta/.config/pokemon-go-map/pogom.db --gmaps-key  XXXXX --token XXXXXX --step-limit 7
**Python: Traceback (most recent call last):
  File "./runserver.py", line 34, in <module>
    from pogom.search import search_overseer_thread, fake_search_loop
  File "/home/kazeta/pokemongomap/resources/app/map/pogom/search.py", line 30, in <module>
    from pgoapi import PGoApi
  File "/home/kazeta/pokemongomap/resources/app/map/pogom/pgoapi/__init__.py", line 39, in <module>
    from .pgoapi import PGoApi
  File "/home/kazeta/pokemongomap/resources/app/map/pogom/pgoapi/pgoapi.py", line 34, in <module>
    from .rpc_api import RpcApi
  File "/home/kazeta/pokemongomap/resources/app/map/pogom/pgoapi/rpc_api.py", line 47, in <module>
    from .utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/home/kazeta/pokemongomap/resources/app/map/pogom/pgoapi/utilities.py", line 37, in <module>
    import xxhash
ImportError: No module named xxhash**

I would thanks some info into correcting this.

**Comment by Krushak42** [comment]
Same problem here :/

**Comment by eritropp** [comment]
next time read release notes. or go back to windows. 
"Linux users will need to install the Python 2 xxhash package"
