### ISSUE TITLE
0.0.7 Stuck at "Waiting" screen

### ISSUE THREAD

**Issue by csinks** [mchristopher/PokemonGo-DesktopMap#78]
Running win 7 x64, 0.0.6 runs great, 0.0.7 logs in, then won't go past a blank white screen with "Waiting" in a box in the center top (held for 10 min, then quit).  I can supply more details if you tell me what you want to know.

**Comment by joereynolds** [comment]
Does the console say anything about Python being unable to open `./example.py`? 
If so, you haven't cloned the repo correctly as `map` is a submodule.

Git clone it with

`git clone --recursive https://github.com/mchristopher/PokemonGo-DesktopMap`

And follow the readme instructions again

**Comment by csinks** [comment]
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.loadURL (Long Filepath\PokemonGoMap-Win\resources\electron.asar\renderer\web-view\web-view.js:409:15)
    at serverUp (file:///long filepath/Downloads/PokemonGoMap-Win/resources/app/main.html:192:21)
    at EventEmitter.<anonymous> (file:///long filepath/Downloads/PokemonGoMap-Win/resources/app/main.html:159:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
