### ISSUE TITLE
Loading, please wait...

### ISSUE THREAD

**Issue by pokeboo1** [mchristopher/PokemonGo-DesktopMap#978]
I now used login via google and after allow I have white window: Loading, please wait...

how fix? thanks.

**Comment by pokeboo1** [comment]
Oh now have error:

Error: connect ECONNREFUSED 127.0.0.1:8000
   at Object.exports._errnoException (util.js:949:11)
   at exports._exceptionWithHostPort (util.js:972:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
