### ISSUE TITLE
starting failed

### ISSUE THREAD

**Issue by Ginso** [mchristopher/PokemonGo-DesktopMap#987]
Hello, i tried to run it on windows 7. i cloned it with git, followed the instructions up to npm install. so far everything worked. But when i try npm start i get errors. Here is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pokemon-go-map@0.2.1~prestart: pokemon-go-map@0.2.1
6 silly lifecycle pokemon-go-map@0.2.1~prestart: no script for prestart, continuing
7 info lifecycle pokemon-go-map@0.2.1~start: pokemon-go-map@0.2.1
8 verbose lifecycle pokemon-go-map@0.2.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle pokemon-go-map@0.2.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Downloads\PokemonGo-DesktopMap\node_modules\.bin;C:\Program Files\nodejs;C:\Users\JETS\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\JETS\bin;C:\Program Files\nodejs;C:\Python27;C:\Python27\Scripts;C:\Python27;C:\Python27\Scripts;C:\Python27;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.7.0_79\bin;C:\program files\basler\pylon 4\pylon\bin\x64;C:\program files\basler\pylon 4\pylon\bin\win32;C:\program files\basler\pylon 4\genicam\bin\win64_x64;C:\program files\basler\pylon 4\pylonc\bin\win32;C:\program files\basler\pylon 4\pylonc\bin\x64;C:\program files\basler\pylon 4\genicam\bin\win32_i86;C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem;C:\Windows\system32\windowspowershell\v1.0;C:\program files\intel\wifi\bin;C:\program files\common files\intel\wirelesscommon;C:\windows\syswow64\empirum;C:\program files (x86)\microsoft sql server\100\tools\binn;C:\program files\microsoft sql server\100\tools\binn;C:\program files\microsoft sql server\100\dts\binn;C:\program files\tortoisesvn\bin;C:\program files (x86)\windows kits\8.1\windows performance toolkit;C:\program files\microsoft sql server\110\tools\binn;C:\program files\microsoft\web platform installer;C:\program files (x86)\microsoft asp.net\asp.net web pages\v1.0;D:\temp\fdk\tools\win;C:\Program Files (x86)\MATLAB\R2006b\bin;C:\Program Files (x86)\MATLAB\R2006b\bin\win32;C:\MinGW\bin;C:\Program Files (x86)\Visual Leak Detector\bin;C:\Program Files (x86)\Skype\Phone;D:\Downloads\apache-ant-1.9.7\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\JETS\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle pokemon-go-map@0.2.1~start: CWD: D:\Downloads\PokemonGo-DesktopMap
11 silly lifecycle pokemon-go-map@0.2.1~start: Args: [ '/d /s /c', 'electron main.js' ]
12 silly lifecycle pokemon-go-map@0.2.1~start: Returned: code: 3221225477  signal: null
13 info lifecycle pokemon-go-map@0.2.1~start: Failed to exec start script
14 verbose stack Error: pokemon-go-map@0.2.1 start: `electron main.js`
14 verbose stack Exit status 3221225477
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pokemon-go-map@0.2.1
16 verbose cwd D:\Downloads\PokemonGo-DesktopMap
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error pokemon-go-map@0.2.1 start: `electron main.js`
22 error Exit status 3221225477
23 error Failed at the pokemon-go-map@0.2.1 start script 'electron main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pokemon-go-map package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pokemon-go-map
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pokemon-go-map
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gempesaw** [comment]
Before doing the `npm install`, did you try the following?

    virtualenv .
    source bin/activate
